apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: investment_analytics
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      configureDatabaseMigration: true
    isDefault: true
    editable: true